added favicon image in the title
Anupkjha2601/food-recipes-website pull request #32
Opened 2023-05-20 08:36 UTC by harshita-2003

Favicon image increased the overall personability of the website in the top section

2023-05-25 19:07 UTC, ydv-ankit requested changes
looks nice but should include favicon in every html file for smooth integration of icon in whole website

2023-05-25 19:08 UTC, ydv-ankit commented on index.html
> +<link rel="icon" href="images/restaurant.png">
correct

2023-05-26 13:12 UTC, harshita-2003 commented
for the smooth integration added favicon to the whole website

2023-05-26 13:15 UTC, ydv-ankit approved these changes
Perfect

2023-05-26 13:31 UTC, harshita-2003 commented
do acknowledge and merge it

2023-05-28 07:58 UTC, Anupkjha2601 approved these changes

2023-05-28 08:00 UTC, merged